site_name: Vocabulary Explorer Docs
site_url: https://ualberta-cmput401.github.io/vocabulary-explorer
repo_url: https://github.com/UAlberta-CMPUT401/vocabulary-explorer


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde


# nav:
#   - Home: index.md
#   - Project Management: ProjectManagement.md
#   - Project Requirements: ProjectRequirements.md
#   - Software Design: SoftwareDesign.md
#   - Teamwork: Teamwork.md
theme: readthedocs